<?php

namespace Tests\Unit\Models;

use App\Models\Gender;
use App\Models\Traits\Uuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use PHPUnit\Framework\TestCase;

class GenderTest extends TestCase
{

    private $gender;
    protected  function setUp (): void {
        parent::setUp (); // TODO: Change the autogenerated stub
        $this->gender = new Gender();
    }

    public function testFillableAttribute()
    {
        $fillable = ['name', 'is_active'];
        $this->assertEquals($fillable, $this->gender->getFillable());
    }

    public function testIdUserTraits()
    {
        $traits = [
            SoftDeletes::class, Uuid::class
        ];

        $genderTraits = array_keys (class_uses (Gender::class));
        $this->assertEquals ($traits, $genderTraits);
    }

    public function testCastsAttribute()
    {
        $casts = ['id' => 'string'];
        $this->assertEquals ($casts, $this->gender->getCasts ());
    }

    public function testIncrementing()
    {
        $this->assertFalse ($this->gender->incrementing);
    }

    public function testDatesAttribute()
    {
        $dates = ['created_at', 'deleted_at', 'updated_at'];

        $this->assertCount (count ($dates), $this->gender->getDates ());
        $this->assertEqualsCanonicalizing ($dates, $this->gender->getDates ());
    }
}
